- name: Installer Bind
  dnf:
    name:
      - bind
      - bind-utils
    state: present
    update_cache: yes

- name: Ouvrir DNS
  ansible.posix.firewalld:
    service: dns
    state: enabled
    permanent: true
    immediate: true
    offline: true
    zone: work
