#SPDX-License-Identifier: MIT-0
---
# tasks file for dns
- name: Installer Bind
  include_tasks: dns.yml
- name: Configurer Bind
  include_tasks: config.yml
- name: Configurer le reseau
  include_tasks: nmcli.yml
